version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
